### ISSUE TITLE
Spotless messes up @snippet

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#591]
Seems spotless doesnt like the `@snippet` tag for Javadoc. This would have been a nice way to fix the issue with #195 .

Before spotless:

![before](https://i.imgur.com/Y8CjP0o.png)

After spotless:

![after](https://i.imgur.com/fTGaUNA.png)

Also renders badly then:

![render](https://i.imgur.com/jKtqadq.png)

**Comment by suryatejess** [comment]
I would like to work on this issue

**Comment by suryatejess** [comment]
I have set up the project locally on my machine and ran `./gradlew spotlessApply`. I cannot reproduce. It is working as expected. 
It's possible this was fixed by upgrades to Spotless or in code changes in the project elsewhere. 

Can you confirm whether there is a still known way to reproduce the bug? 


Talking about #195 , ( `@` -> `&#64;` which is still happening now ) 
As per my research, the reason "@" are turning out into "&#64;" is HTML entities. 

Spotless has nothing do with why it is getting converted. It is because we are using eclipse("4.31"). 
Eclipse escapes `@` inside the \<pre> tag i.e. convert `@` -> `&#64;`

**Comment by Zabuzard** [comment]
@suryatejess 
The problem is still there. See the class `SlashCommandAdapter`.

![issue](https://i.vgy.me/n1g1Aa.png)

The idiomatic way to write code in Javadoc is by using `{@snippet : ... }` and if you use that here, it also works:

![works](https://i.vgy.me/TH9m2t.png)

But then spotless messes it up when executed. So we temporarily went for the alternative with `<pre>...</pre>` which is worse but at least spotless only messes it up partially. But there it also messes up `@`.

Ideally we want `{@snippet : ...}` to work as shown in this issue.
